const name = {
  "jdiperi88@gmail.com": "Joey DiPeri",
  "sdiperi17@gmail.com": "Saida DiPeri",
  "tyronesanderson@yahoo.com": "Tyrone Sanderson",
  "amateo921@gmail.com": "Alejandra Mateo",
  "allisonlcasey@gmail.com": "Allison Casey",
  "anne.elshafei@yahoo.com": "Anne Elshafei",
  "annettecasey722@gmail.com": "Annette Casey",
  "arnold.kim76@gmail.com": "Arnold Kim",
  "dbertolino@houlihanlawrence.com": "Aunt Denise",
  "bianca.cortes926@gmail.com": "Bianca Cortes",
  "candiced0126@gmail.com": "Candice",
  "work.sopova@gmail.com": "Christina Sopova",
  "danmarraffini@gmail.com": "Dan Marraffini",
  "danicodes94@gmail.com": "Danielle Williams",
  "dgao10@gmail.com": "De Gao",
  "dennis.luo1@gmail.com": "Dennis Luo",
  "edwardehayward8787@gmail.com": "Edward Hayward",
  "sassy2582@yahoo.com": "Erica Bortnowski",
  "fdiperi@yahoo.com": "Frank DiPeri",
  "jbaksies23@yahoo.com": "Jess Baker",
  "joe.porto@inmarketingservices.com": "Joe Porto",
  "john.t.du@gmail.com": "John Du",
  "kryssy77@gmail.com": "Kryssy Hines",
  "mrntcoleman@gmail.com": "Marion Coleman",
  "marthavelazquez26@hotmail.com": "Martha Velazquez",
  "merricklee@me.com": "Merrick Lee",
  "truth531@gmail.com": "Mitch Severe",
  "merjen.ch@gmail.com": "Mj Ch",
  "mauracat@aol.com": "Cricket Casey",
  "magnardotavarez@gmail.com": "Nando",
  "nikkise@outlook.com": "Nikki Severe",
  "pamyk.ch@gmail.com": "Pam Ch",
  "miprincie@gmail.com": "Princie",
  "prshantbatra@gmail.com": "Prshant Batra",
  "rajisteb@gmail.com": "Raj Bennin",
  "rob.cifre@inmarketingservices.com": "Rob Cifre",
  "ryan.carroll@inmarketingservices.com": "Ryan Carroll",
  "scott.m.allison@icloud.com": "Scott Allison",
  "shuai.z1988@gmail.com": "Shuai",
  "steve.sanborn@inmarketingservices.com": "Steve Sanborn",
  "tami.gomez@inmarketingservices.com": "Tami Gomez",
  "trueifandonlyif@gmail.com": "Tiffany Casey",
  "oswaldo.almazo@gmail.com": "Oswaldo Almazo",
  "francisco.ashley1@gmail.com": "Ashley Francisco",
  "ca9488@gmail.com": "Claudia Arias",
  "Sandiimayeguahi@gmail.com": "Sandi Mayeguahi",
  "asheberarlain@gmail.com": "Asheber Arlain",
  "erikasequ@gmail.com": "Ericka Sequiera"
};

module.exports = email => {
  return name[email];
};
